### ISSUE TITLE
mysql_connect missing

### ISSUE THREAD

**Issue by eagl3s1ght** [tareq1988/wp-docker#3]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/web/wp/wp-includes/wp-db.php on line 1562

seems dockerfile isnt installing the php mysql functions correctly.
i had to run `docker exec -it php docker-php-ext-install pdo_mysql` and then `docker restart php`, and get fresh cache by adding ?a=a to url

**Comment by tareq1988** [comment]
I think that's because of docker-compose issue. PHP and Nginx needs to wait before Mariadb is ready, fixed now.
